import React, { useState } from 'react';
import { generateDailyInsights } from '../services/geminiService';
import { Sparkles, TrendingUp, TrendingDown, RefreshCw, CheckCircle2, Bot, AlertTriangle } from 'lucide-react';

export default function AIInsights() {
  const [loading, setLoading] = useState(false);
  const [insightsData, setInsightsData] = useState({
    insights: [
      "Road complaints increased by 38% following overnight heavy rains in Ward 18",
      "Drainage overflow complaints clustered heavily in Ward 7 near school zone",
      "Water leakage issues repeated across 5 streets in Ward 12",
      "Garbage collection grievances reduced by 12% post morning clean drive",
      "Streetlight blackouts reported in commercial zone Ward 4"
    ],
    predictions: {
      roads: "+14%",
      drainage: "-8%",
      water: "+5%",
      garbage: "-12%"
    }
  });

  const handleRefresh = async () => {
    setLoading(true);
    // Simulate live Gemini prompt execution
    setTimeout(() => {
      setInsightsData({
        insights: [
          "Road complaints spiked by 42% in Ward 18 following monsoon runoff",
          "Drainage bottleneck detected at Ward 7 intersection requiring immediate de-silting",
          "Water supply pressure restored in 3 key residential sectors of Ward 12",
          "Garbage pickup efficiency improved by 15% after route optimization",
          "Streetlight repair crew cleared 18 pending tickets in Ward 4"
        ],
        predictions: {
          roads: "+18%",
          drainage: "-10%",
          water: "+3%",
          garbage: "-15%"
        }
      });
      setLoading(false);
    }, 1000);
  };

  return (
    <div class="max-w-6xl mx-auto px-4 py-8 space-y-6">
      
      {/* Header */}
      <div class="gov-card p-6 border-l-4 border-l-amber-500 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div class="flex items-center gap-2">
            <span class="px-2.5 py-0.5 bg-amber-500/20 text-amber-300 text-xs font-bold rounded-full border border-amber-500/40 flex items-center gap-1">
              <Sparkles class="w-3.5 h-3.5" /> GENERATED BY GEMINI 2.5
            </span>
            <h2 class="text-xl font-bold text-white">Daily Municipal AI Insights & Trends</h2>
          </div>
          <p class="text-xs text-slate-400 mt-1">Autonomous daily summary reports and predictive trend forecasts for governance</p>
        </div>

        <button 
          onClick={handleRefresh}
          disabled={loading}
          class="px-4 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white font-extrabold text-xs rounded-xl shadow-lg flex items-center gap-2 transition hover:scale-105"
        >
          <RefreshCw class={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} /> Generate New AI Insights
        </button>
      </div>

      {/* Predictive Analytics Cards (Next Week Trend Forecasts) */}
      <div>
        <h3 class="text-sm font-bold text-slate-300 uppercase tracking-wider mb-3 flex items-center gap-2">
          <TrendingUp class="w-4 h-4 text-blue-400" /> AI Predictive Trend Analytics (Next Week Forecast)
        </h3>

        <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
          
          <div class="bg-slate-900 p-4 rounded-xl border border-red-500/30">
            <p class="text-xs text-slate-400 font-semibold">Road Complaints</p>
            <div class="text-2xl font-extrabold text-red-400 mt-1 flex items-center gap-1">
              <TrendingUp class="w-5 h-5" /> {insightsData.predictions.roads}
            </div>
            <p class="text-[10px] text-slate-400 mt-1">Monsoon rainfall correlation</p>
          </div>

          <div class="bg-slate-900 p-4 rounded-xl border border-emerald-500/30">
            <p class="text-xs text-slate-400 font-semibold">Drainage Overflow</p>
            <div class="text-2xl font-extrabold text-emerald-400 mt-1 flex items-center gap-1">
              <TrendingDown class="w-5 h-5" /> {insightsData.predictions.drainage}
            </div>
            <p class="text-[10px] text-slate-400 mt-1">Post de-silting improvement</p>
          </div>

          <div class="bg-slate-900 p-4 rounded-xl border border-amber-500/30">
            <p class="text-xs text-slate-400 font-semibold">Water Leakage</p>
            <div class="text-2xl font-extrabold text-amber-400 mt-1 flex items-center gap-1">
              <TrendingUp class="w-5 h-5" /> {insightsData.predictions.water}
            </div>
            <p class="text-[10px] text-slate-400 mt-1">Aging pipeline strain</p>
          </div>

          <div class="bg-slate-900 p-4 rounded-xl border border-blue-500/30">
            <p class="text-xs text-slate-400 font-semibold">Garbage Grievances</p>
            <div class="text-2xl font-extrabold text-blue-400 mt-1 flex items-center gap-1">
              <TrendingDown class="w-5 h-5" /> {insightsData.predictions.garbage}
            </div>
            <p class="text-[10px] text-slate-400 mt-1">Optimized sanitation routes</p>
          </div>

        </div>
      </div>

      {/* Bullet Insights Panel */}
      <div class="gov-card p-6 space-y-4">
        <h3 class="font-bold text-base text-white flex items-center gap-2 border-b border-slate-800 pb-3">
          <Bot class="w-5 h-5 text-blue-400" /> Today's Actionable Municipal Insights
        </h3>

        <div class="space-y-3">
          {insightsData.insights.map((insight, idx) => (
            <div key={idx} class="p-4 rounded-xl bg-slate-950/70 border border-slate-800 flex items-start gap-3">
              <span class="w-2 h-2 rounded-full bg-blue-400 mt-2 flex-shrink-0"></span>
              <p class="text-xs text-slate-200 leading-relaxed font-medium">{insight}</p>
            </div>
          ))}
        </div>
      </div>

    </div>
  );
}
