declare module 'lucide-react' {
  import * as React from 'react';

  export type LucideProps = React.SVGProps<SVGSVGElement> & {
    size?: number | string;
    color?: string;
    strokeWidth?: number | string;
    className?: string;
    absoluteStrokeWidth?: boolean;
  };

  export type LucideIcon = React.ComponentType<LucideProps>;
  export type Icon = LucideIcon;

  export const Shield: LucideIcon;
  export const Droplets: LucideIcon;
  export const Zap: LucideIcon;
  export const Construction: LucideIcon;
  export const HeartPulse: LucideIcon;
  export const Landmark: LucideIcon;
  export const Bus: LucideIcon;
  export const GraduationCap: LucideIcon;
  export const Building2: LucideIcon;
  export const Menu: LucideIcon;
  export const X: LucideIcon;
  export const Languages: LucideIcon;
  export const Search: LucideIcon;
  export const CalendarClock: LucideIcon;
  export const UserCheck: LucideIcon;
  export const Radio: LucideIcon;
  export const Loader2: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const FilePlus2: LucideIcon;
  export const Bell: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const Clock3: LucideIcon;
  export const CircleCheckBig: LucideIcon;
  export const Activity: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const UserPlus: LucideIcon;
  export const LogIn: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const Lock: LucideIcon;
  export const MapPin: LucideIcon;
  export const Crosshair: LucideIcon;
  export const Upload: LucideIcon;
  export const Mic: LucideIcon;
  export const FileText: LucideIcon;
  export const Image: LucideIcon;
  export const Video: LucideIcon;
  export const Sparkles: LucideIcon;
  export const LogOut: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const Mail: LucideIcon;
  export const Phone: LucideIcon;
  export const User: LucideIcon;
  export const MessageSquareMore: LucideIcon;
  export const Send: LucideIcon;
  export const Bot: LucideIcon;
  export const CheckCheck: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const Timer: LucideIcon;
  export const Check: LucideIcon;
  export const Cpu: LucideIcon;
  export const BrainCircuit: LucideIcon;
  export const ListTree: LucideIcon;
  export const ClipboardCheck: LucideIcon;
  export const Wrench: LucideIcon;
  export const Radar: LucideIcon;
  export const Star: LucideIcon;
  export const Quote: LucideIcon;
  export const Route: LucideIcon;
  export const Facebook: LucideIcon;
  export const Twitter: LucideIcon;
  export const Youtube: LucideIcon;
  export const Instagram: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const ChevronDownIcon: LucideIcon;
  export const ChevronLeftIcon: LucideIcon;
  export const ChevronRightIcon: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const Minus: LucideIcon;
  export const Circle: LucideIcon;
  export const GripVertical: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const PanelLeft: LucideIcon;
  export const ChevronLeft: LucideIcon;

  const content: any;
  export default content;
}
