/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TrackRouteImport } from './routes/track'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenFileRouteImport } from './routes/citizen.file'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as OfficerAiAssistantRouteImport } from './routes/officer.ai-assistant'
import { Route as OfficerBudgetRouteImport } from './routes/officer.budget'
import { Route as OfficerEligibilityRouteImport } from './routes/officer.eligibility'
import { Route as OfficerFundingRouteImport } from './routes/officer.funding'
import { Route as OfficerGrievancesRouteImport } from './routes/officer.grievances'
import { Route as OfficerLoginRouteImport } from './routes/officer.login'
import { Route as OfficerMapRouteImport } from './routes/officer.map'
import { Route as OfficerPatternsRouteImport } from './routes/officer.patterns'
import { Route as OfficerPrioritizationRouteImport } from './routes/officer.prioritization'
import { Route as OfficerRecommendationsRouteImport } from './routes/officer.recommendations'
import { Route as OfficerReportsRouteImport } from './routes/officer.reports'
import { Route as OfficerRootCauseRouteImport } from './routes/officer.root-cause'
import { Route as OfficerWorkforceRouteImport } from './routes/officer.workforce'
import { Route as OfficerComplaintsIdRouteImport } from './routes/officer.complaints.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/citizen/',
  path: '/citizen/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenFileRoute = CitizenFileRouteImport.update({
  id: '/citizen/file',
  path: '/citizen/file',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/officer/',
  path: '/officer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerAiAssistantRoute = OfficerAiAssistantRouteImport.update({
  id: '/officer/ai-assistant',
  path: '/officer/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerBudgetRoute = OfficerBudgetRouteImport.update({
  id: '/officer/budget',
  path: '/officer/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerEligibilityRoute = OfficerEligibilityRouteImport.update({
  id: '/officer/eligibility',
  path: '/officer/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerFundingRoute = OfficerFundingRouteImport.update({
  id: '/officer/funding',
  path: '/officer/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerGrievancesRoute = OfficerGrievancesRouteImport.update({
  id: '/officer/grievances',
  path: '/officer/grievances',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerLoginRoute = OfficerLoginRouteImport.update({
  id: '/officer/login',
  path: '/officer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerMapRoute = OfficerMapRouteImport.update({
  id: '/officer/map',
  path: '/officer/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerPatternsRoute = OfficerPatternsRouteImport.update({
  id: '/officer/patterns',
  path: '/officer/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerPrioritizationRoute = OfficerPrioritizationRouteImport.update({
  id: '/officer/prioritization',
  path: '/officer/prioritization',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRecommendationsRoute = OfficerRecommendationsRouteImport.update({
  id: '/officer/recommendations',
  path: '/officer/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerReportsRoute = OfficerReportsRouteImport.update({
  id: '/officer/reports',
  path: '/officer/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRootCauseRoute = OfficerRootCauseRouteImport.update({
  id: '/officer/root-cause',
  path: '/officer/root-cause',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerWorkforceRoute = OfficerWorkforceRouteImport.update({
  id: '/officer/workforce',
  path: '/officer/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerComplaintsIdRoute = OfficerComplaintsIdRouteImport.update({
  id: '/officer/complaints/$id',
  path: '/officer/complaints/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/citizen/file': typeof CitizenFileRoute
  '/officer/ai-assistant': typeof OfficerAiAssistantRoute
  '/officer/budget': typeof OfficerBudgetRoute
  '/officer/eligibility': typeof OfficerEligibilityRoute
  '/officer/funding': typeof OfficerFundingRoute
  '/officer/grievances': typeof OfficerGrievancesRoute
  '/officer/login': typeof OfficerLoginRoute
  '/officer/map': typeof OfficerMapRoute
  '/officer/patterns': typeof OfficerPatternsRoute
  '/officer/prioritization': typeof OfficerPrioritizationRoute
  '/officer/recommendations': typeof OfficerRecommendationsRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/root-cause': typeof OfficerRootCauseRoute
  '/officer/workforce': typeof OfficerWorkforceRoute
  '/citizen/': typeof CitizenIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/officer/complaints/$id': typeof OfficerComplaintsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/citizen/file': typeof CitizenFileRoute
  '/officer/ai-assistant': typeof OfficerAiAssistantRoute
  '/officer/budget': typeof OfficerBudgetRoute
  '/officer/eligibility': typeof OfficerEligibilityRoute
  '/officer/funding': typeof OfficerFundingRoute
  '/officer/grievances': typeof OfficerGrievancesRoute
  '/officer/login': typeof OfficerLoginRoute
  '/officer/map': typeof OfficerMapRoute
  '/officer/patterns': typeof OfficerPatternsRoute
  '/officer/prioritization': typeof OfficerPrioritizationRoute
  '/officer/recommendations': typeof OfficerRecommendationsRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/root-cause': typeof OfficerRootCauseRoute
  '/officer/workforce': typeof OfficerWorkforceRoute
  '/citizen': typeof CitizenIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/officer/complaints/$id': typeof OfficerComplaintsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/citizen/file': typeof CitizenFileRoute
  '/officer/ai-assistant': typeof OfficerAiAssistantRoute
  '/officer/budget': typeof OfficerBudgetRoute
  '/officer/eligibility': typeof OfficerEligibilityRoute
  '/officer/funding': typeof OfficerFundingRoute
  '/officer/grievances': typeof OfficerGrievancesRoute
  '/officer/login': typeof OfficerLoginRoute
  '/officer/map': typeof OfficerMapRoute
  '/officer/patterns': typeof OfficerPatternsRoute
  '/officer/prioritization': typeof OfficerPrioritizationRoute
  '/officer/recommendations': typeof OfficerRecommendationsRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/root-cause': typeof OfficerRootCauseRoute
  '/officer/workforce': typeof OfficerWorkforceRoute
  '/citizen/': typeof CitizenIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/officer/complaints/$id': typeof OfficerComplaintsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/track'
    | '/citizen/file'
    | '/officer/ai-assistant'
    | '/officer/budget'
    | '/officer/eligibility'
    | '/officer/funding'
    | '/officer/grievances'
    | '/officer/login'
    | '/officer/map'
    | '/officer/patterns'
    | '/officer/prioritization'
    | '/officer/recommendations'
    | '/officer/reports'
    | '/officer/root-cause'
    | '/officer/workforce'
    | '/citizen/'
    | '/officer/'
    | '/officer/complaints/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/track'
    | '/citizen/file'
    | '/officer/ai-assistant'
    | '/officer/budget'
    | '/officer/eligibility'
    | '/officer/funding'
    | '/officer/grievances'
    | '/officer/login'
    | '/officer/map'
    | '/officer/patterns'
    | '/officer/prioritization'
    | '/officer/recommendations'
    | '/officer/reports'
    | '/officer/root-cause'
    | '/officer/workforce'
    | '/citizen'
    | '/officer'
    | '/officer/complaints/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/track'
    | '/citizen/file'
    | '/officer/ai-assistant'
    | '/officer/budget'
    | '/officer/eligibility'
    | '/officer/funding'
    | '/officer/grievances'
    | '/officer/login'
    | '/officer/map'
    | '/officer/patterns'
    | '/officer/prioritization'
    | '/officer/recommendations'
    | '/officer/reports'
    | '/officer/root-cause'
    | '/officer/workforce'
    | '/citizen/'
    | '/officer/'
    | '/officer/complaints/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TrackRoute: typeof TrackRoute
  CitizenFileRoute: typeof CitizenFileRoute
  OfficerAiAssistantRoute: typeof OfficerAiAssistantRoute
  OfficerBudgetRoute: typeof OfficerBudgetRoute
  OfficerEligibilityRoute: typeof OfficerEligibilityRoute
  OfficerFundingRoute: typeof OfficerFundingRoute
  OfficerGrievancesRoute: typeof OfficerGrievancesRoute
  OfficerLoginRoute: typeof OfficerLoginRoute
  OfficerMapRoute: typeof OfficerMapRoute
  OfficerPatternsRoute: typeof OfficerPatternsRoute
  OfficerPrioritizationRoute: typeof OfficerPrioritizationRoute
  OfficerRecommendationsRoute: typeof OfficerRecommendationsRoute
  OfficerReportsRoute: typeof OfficerReportsRoute
  OfficerRootCauseRoute: typeof OfficerRootCauseRoute
  OfficerWorkforceRoute: typeof OfficerWorkforceRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
  OfficerComplaintsIdRoute: typeof OfficerComplaintsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/citizen'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/file': {
      id: '/citizen/file'
      path: '/citizen/file'
      fullPath: '/citizen/file'
      preLoaderRoute: typeof CitizenFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/': {
      id: '/officer/'
      path: '/officer'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/ai-assistant': {
      id: '/officer/ai-assistant'
      path: '/officer/ai-assistant'
      fullPath: '/officer/ai-assistant'
      preLoaderRoute: typeof OfficerAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/budget': {
      id: '/officer/budget'
      path: '/officer/budget'
      fullPath: '/officer/budget'
      preLoaderRoute: typeof OfficerBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/eligibility': {
      id: '/officer/eligibility'
      path: '/officer/eligibility'
      fullPath: '/officer/eligibility'
      preLoaderRoute: typeof OfficerEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/funding': {
      id: '/officer/funding'
      path: '/officer/funding'
      fullPath: '/officer/funding'
      preLoaderRoute: typeof OfficerFundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/grievances': {
      id: '/officer/grievances'
      path: '/officer/grievances'
      fullPath: '/officer/grievances'
      preLoaderRoute: typeof OfficerGrievancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/login': {
      id: '/officer/login'
      path: '/officer/login'
      fullPath: '/officer/login'
      preLoaderRoute: typeof OfficerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/map': {
      id: '/officer/map'
      path: '/officer/map'
      fullPath: '/officer/map'
      preLoaderRoute: typeof OfficerMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/patterns': {
      id: '/officer/patterns'
      path: '/officer/patterns'
      fullPath: '/officer/patterns'
      preLoaderRoute: typeof OfficerPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/prioritization': {
      id: '/officer/prioritization'
      path: '/officer/prioritization'
      fullPath: '/officer/prioritization'
      preLoaderRoute: typeof OfficerPrioritizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/recommendations': {
      id: '/officer/recommendations'
      path: '/officer/recommendations'
      fullPath: '/officer/recommendations'
      preLoaderRoute: typeof OfficerRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/reports': {
      id: '/officer/reports'
      path: '/officer/reports'
      fullPath: '/officer/reports'
      preLoaderRoute: typeof OfficerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/root-cause': {
      id: '/officer/root-cause'
      path: '/officer/root-cause'
      fullPath: '/officer/root-cause'
      preLoaderRoute: typeof OfficerRootCauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/workforce': {
      id: '/officer/workforce'
      path: '/officer/workforce'
      fullPath: '/officer/workforce'
      preLoaderRoute: typeof OfficerWorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/complaints/$id': {
      id: '/officer/complaints/$id'
      path: '/officer/complaints/$id'
      fullPath: '/officer/complaints/$id'
      preLoaderRoute: typeof OfficerComplaintsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TrackRoute: TrackRoute,
  CitizenFileRoute: CitizenFileRoute,
  OfficerAiAssistantRoute: OfficerAiAssistantRoute,
  OfficerBudgetRoute: OfficerBudgetRoute,
  OfficerEligibilityRoute: OfficerEligibilityRoute,
  OfficerFundingRoute: OfficerFundingRoute,
  OfficerGrievancesRoute: OfficerGrievancesRoute,
  OfficerLoginRoute: OfficerLoginRoute,
  OfficerMapRoute: OfficerMapRoute,
  OfficerPatternsRoute: OfficerPatternsRoute,
  OfficerPrioritizationRoute: OfficerPrioritizationRoute,
  OfficerRecommendationsRoute: OfficerRecommendationsRoute,
  OfficerReportsRoute: OfficerReportsRoute,
  OfficerRootCauseRoute: OfficerRootCauseRoute,
  OfficerWorkforceRoute: OfficerWorkforceRoute,
  CitizenIndexRoute: CitizenIndexRoute,
  OfficerIndexRoute: OfficerIndexRoute,
  OfficerComplaintsIdRoute: OfficerComplaintsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
